POST http://localhost:5000/users
Content-Type: application/json

{
  "firstName": "User",
  "lastName": "Userenko",
  "email": "user@mail.com",
  "password": "1234Test",
  "passwordRepeat": "1234Test",
  "isMale": true
}