GET http://localhost:5000/secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjIxNTMwMzAzMjg3M2QyODdjMWI2ODIiLCJpYXQiOjE3MTM4MDcxNDYsImV4cCI6MTcxMzgwNzE3Nn0.nAHDZi0KI8kzv_FCC9CPBxDATtdRm0nNjXXErdMN33g