POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjIxNTMwMzAzMjg3M2QyODdjMWI2ODIiLCJpYXQiOjE3MTM1NDkxMzIsImV4cCI6MTcxMzYzNTUzMn0.BKLRiFDDZxQWuTgDNiPN2qf_cwjyGAY_Sd8W7SYmFCE"
}