POST http://localhost:5000/auth/registration
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Testenko",
  "email": "test1@mail.com",
  "password": "admin",
  "passwordRepeat": "admin",
  "isMale": true
}